module.exports = {
    mods: 'mods',
    general: 'general',
    offtopic: 'offtopic',
    cs50: 'cs50',
    beginners: 'beginners',
    math: 'math',
    java: 'java',
    python: 'python',
    php: 'php',
    c_cpp: 'c_cpp',
    dotnet: 'dotnet',
    ruby: 'ruby',
    webdev: 'webdev',
    webdesign: 'webdesign',
    graphics: 'graphics',
    mobiledev: 'mobiledev',
    gamedev: 'gamedev',
  };
